(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(setq default-buffer-file-coding-system 'utf-8)
(setq gc-cons-threshold most-positive-fixnum)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(menu-bar-mode -1)
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode t)
(setq-default  cursor-type 'bar)
(setq inhibit-splash-screen 1)
(set-face-attribute 'default nil :height 160)
(show-paren-mode 1)
(electric-pair-mode t)
(provide 'init-ui)
